# Generated by Django 3.0.6 on 2023-06-20 19:59

import api.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershow',
            name='code',
            field=models.CharField(
                default=api.models, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='usershow',
            name='watched_episodes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
