# Generated by Django 3.0.6 on 2023-06-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_usershow_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershow',
            name='watched_episodes',
            field=models.IntegerField(),
        ),
    ]
