# Generated by Django 3.0.6 on 2023-06-22 21:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230623_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershow',
            name='watched_episodes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
