# Generated by Django 4.1 on 2023-06-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20230623_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershow',
            name='season',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
