# Generated by Django 4.1 on 2023-08-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_usershow_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershow',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
