# Generated by Django 3.0.6 on 2024-01-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20240128_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershow',
            name='apiSeason',
            field=models.IntegerField(default=-1),
        ),
    ]
